# Generated by Django 2.1.3 on 2018-11-20 12:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('todo', '0002_todolist'),
    ]

    operations = [
        migrations.CreateModel(
            name='Todo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=72)),
                ('body', models.CharField(max_length=140)),
            ],
        ),
        migrations.DeleteModel(
            name='TodoList',
        ),
    ]
